server:
  port: 88081

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.182.128/guli_pms?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    initialSize: 5  #初始建立连接数量
    minIdle: 5  #最小连接数量
    maxActive: 20 #最大连接数量
    maxWait: 100000  #获取连接最大等待时间，毫秒
    testOnBorrow: true #申请连接时检测连接是否有效
    testOnReturn: false #归还连接时检测连接是否有效
    timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
    minEvictableIdleTimeMillis: 300000  #连接在连接池的最小生存时间（毫秒）
  redis:
    host: 192.168.182.128
